
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Nov 17 11:27:13 GMT-05:00 2024
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Parentesis_c = 22;
  public static final int Parentesis_a = 21;
  public static final int Compromiso = 10;
  public static final int Distancia = 12;
  public static final int Numero = 30;
  public static final int Corchete_c = 26;
  public static final int Op_booleano = 20;
  public static final int ERROR = 31;
  public static final int Corchete_a = 25;
  public static final int Identificador = 29;
  public static final int Dividimos = 14;
  public static final int Comillas = 3;
  public static final int SiMeAmas = 9;
  public static final int Llave_c = 24;
  public static final int Llave_a = 23;
  public static final int SiempreContigo = 6;
  public static final int Op_relacional = 17;
  public static final int P_coma = 28;
  public static final int T_dato = 4;
  public static final int EOF = 0;
  public static final int TeDedicoMiTiempo = 7;
  public static final int Division = 15;
  public static final int Op_incremento = 19;
  public static final int Op_atribucion = 18;
  public static final int Fuerza = 13;
  public static final int Linea = 2;
  public static final int error = 1;
  public static final int Op_logico = 16;
  public static final int Relacion = 27;
  public static final int PeroTeEntiendo = 5;
  public static final int TePrometo = 8;
  public static final int Juntos = 11;
}

